name: Zurna Dürüm AI APK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları indir
        uses: actions/checkout@v4

      - name: APK oluştur
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: APK'yı sakla
        uses: actions/upload-artifact@v4
        with:
          name: zurna-durum-ai-apk
          path: ${{ steps.buildozer.outputs.filename }}
